### ISSUE TITLE
Error when using StoryShot: Unexpected token import

### ISSUE THREAD

**Issue by jnhooper** [tuchk4/storybook-readme#172]
First thanks for this awesome tool! 
I'm trying to setup storyshots and I'm running into issues with jest not liking a certain file in the storybook-readme node module. I tried following the same jest config posted [here](https://github.com/tuchk4/storybook-readme/blob/master/packages/example-react/jest.config.js) But i still get the same error:
```
● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/<pathToProject>/node_modules/storybook-readme/styles/codeThemeCss.js:28
      import("./prismCodeThemes/".concat(codeTheme, ".css.js")).then(function (t) {
      ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/storybook-readme/components/ReadmeContent/index.js:36:44)

```

jest.config.js
```
module.exports = {
  browser: true,
  testURL: 'http://localhost',
  transform: {
    '^.+\\.md?$': 'markdown-loader-jest',
    '^.+\\.js?$': 'babel-jest'
  },
  transformIgnorePatterns: ['/node_modules/(?!(@babel/runtime)/).*/']
};
```

**Comment by tuchk4** [comment]
Seems you are running old version try `5.0.3`

https://github.com/tuchk4/storybook-readme/issues/134#issuecomment-488839874

**Comment by jnhooper** [comment]
🤦‍♂ Thanks a ton!
