### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by amcdnl** [tuchk4/storybook-readme#47]
Storybook now supports Angular, as such it would be awesome if this library were to implement it too.

**Comment by tuchk4** [comment]
Yeah, I am going to add Angular support a bit later

**Comment by amcdnl** [comment]
It actually works, should probably just update readmes.

**Comment by amorenew** [comment]
@amcdnl how you make it work
I got error import README1 from '../src/framework/content/README1.md';
`error TS2307: Cannot find module '../src/framework/content/README1.md'.`
![image](https://user-images.githubusercontent.com/2842459/35622048-80ae5544-0697-11e8-9d4f-fd547f5f17cc.png)

**Comment by amcdnl** [comment]
Add this:

```
declare module '*.md';
```

**Comment by amorenew** [comment]
@amcdnl in wepback or where I add this line
if it is in webpack could you share it?

**Comment by amcdnl** [comment]
No, just in a root ts file.

**Comment by tuchk4** [comment]
@amcdnl  Is it work correctly?
Seems `withDocs` method can not work :) only `withReadme`

**Comment by MatissJanis** [comment]
Hey,

`withReadme` works just fine, but `withDocs` seems to break for me as well.

**Comment by andrei-ilyukovich** [comment]
@tuchk4 do you have any updates on fully support for Angular?

**Comment by andrei-ilyukovich** [comment]
Also it would be fine to have support for highlighting typescript blocks of code, most of the angular projects use this language. As far as I understand it is quite simple to just add `import 'prismjs/components/prism-typescript';` in **highlite.js** file. What do you think, @tuchk4 ?

**Comment by tuchk4** [comment]
@andrei-ilyukovich right now I have no time to update code to fully support angular.

But I would be happy for any help.

**Comment by anneke** [comment]
Thank you for considering adding support for Angular. I wish I had the skills to add support, but unfortunately no can do. If anyone will try their hand at this, you have a fan right here!
I would also just appreciate a example snippet or a PR made to the readme on how to use it in Angular, if (part of it) already works :) @amcdnl

**Comment by danielpcampagna** [comment]
Using with `.addDecorator(withReadme(MyComponent))` I got this error :

```
storybook-readme: wrong arguments
    Error: storybook-readme: wrong arguments
    at http://localhost:9001/static/iframe.bundle.js:195912:15
    at Object.withReadme (http://localhost:9001/static/iframe.bundle.js:195918:70)
    at Object.<anonymous> (http://localhost:9001/static/iframe.bundle.js:202257:38)
    at Object../src/app/components/menu-applications/applications-menu.stories.ts (http://localhost:9001/static/iframe.bundle.js:202293:30)
    at __webpack_require__ (http://localhost:9001/static/iframe.bundle.js:725:30)
    at fn (http://localhost:9001/static/iframe.bundle.js:102:20)
    at webpackContext (http://localhost:9001/static/iframe.bundle.js:201761:9)
    at http://localhost:9001/static/iframe.bundle.js:828:12
    at Array.forEach (<anonymous>)
```

My code is like this:

```javascript
storiesOf('Menu de Aplicacoes', module)
   .addDecorator(moduleMetadata({ ... })
   .addDecorator(withReadme(MyComponent))
   .add('Basic', () => ({ ... }));
```

**Comment by blinkcat** [comment]
the first parameter passed to the withReadme, should be your readme file, not your component.   
 [doc](https://github.com/tuchk4/storybook-readme#use-as-decorator). @danielpcampagna

**Comment by athergeek** [comment]
Is the full Angular support completed ?
