### ISSUE TITLE
Got error when using vue support

### ISSUE THREAD

**Issue by DrSensor** [tuchk4/storybook-readme#49]
Error message
```
Cannot add property components, object is not extensible
    
      TypeError: Cannot add property components, object is not extensible
    at eval (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/client_api.js:127:39)
    at story (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/client_api.js:124:22)
    at eval (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/client_api.js:128:70)
    at renderMain (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/render.js:104:27)
    at renderPreview (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/render.js:132:12)
    at renderUI (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/index.js:88:26)
    at Object.dispatch (webpack-internal:///./node_modules/redux/es/createStore.js:178:7)
    at ConfigApi._renderMain (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/config_api.js:47:24)
    at render (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/config_api.js:66:17)
    at ConfigApi.configure (webpack-internal:///./node_modules/@storybook/vue/dist/client/preview/config_api.js:91:9)
```

snippet
```jsx
    const story = () => {
      return {
        render () {
          return <story onAction={action(`${storyName}/${componentName}`)} />
        },
        components: {
          'story': Component
        }
      }
    }

    let storyWithAddons = story

    storyWithAddons = withDocs(Component.__docs || '<!-- STORY -->', storyWithAddons)

    storiesOf(storyName, module).add(componentName, storyWithAddons)
```

Something todo with `        components: {
          'story': Component
        }` ?

**Comment by tuchk4** [comment]
I will able to reproduce it and fix only in 1-2 weeks (because I am on vacation right now)

**Comment by tuchk4** [comment]
@DrSensor Seems this is because of using `render()` method to return template.
It should work correctly with `tempalate:` attr like in [this example](https://github.com/tuchk4/storybook-readme/blob/master/packages/example-vue/stories/index.js#L53)

Could you please check it?

--

I did not find any example with `render()` method at [storybook docs](https://storybook.js.org/basics/guide-vue/#write-your-stories). Could you please share any link with examples so I can try to adapt this approach to render stories.

**Comment by DrSensor** [comment]
[Here](https://github.com/storybooks/storybook/blob/master/examples/vue-kitchen-sink/src/stories/custom-rendering.stories.js#L39) is the official example (but not yet documented) using `render()` function.

I have checked in my real case scenario [here](https://github.com/DrSensor/vue-annotator/blob/master/src/stories/index.js#L55) and still got that error.
Sorry, can create the minimal example for now because latest `@vue/cli` just does huge breaking changes so then I can't use command `getstorybook` out-of-the-box without tinkering a bit.

**Comment by tuchk4** [comment]
Added story with JSX to examples https://github.com/tuchk4/storybook-readme/blob/master/packages/example-vue/stories/index.js#L188

Can not reproduce

**Comment by tuchk4** [comment]
Close for now. Reopen or create new one if there are more details how to repro.
