### ISSUE TITLE
Error when loading Readme that have image

### ISSUE THREAD

**Issue by DrSensor** [tuchk4/storybook-readme#51]
Error when loading Readme that has gif (in my case). 
When I remove `![](./static/screenplay.gif)`, it builds successfully.

```bash
yarn run v1.2.1
$ build-storybook --static-dir static --output-dir .storybook/dist
@storybook/vue v3.3.10

=> Loading custom addons config.
=> Loading custom webpack config (full-control mode).
=> Copying static files from: static
Building storybook ...
Failed to build the storybook
./static/screenplay.gif
Module parse failed: Unexpected character '' (1:7)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./README.md 1:257-291
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/vue/dist/server/config/polyfills.js ./node_modules/@storybook/vue/dist/server/config/globals.js ./.storybook/config.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

my `.storybook/webpack.config.js`
```js
const updateWebpackConfig = require('storybook-readme/env/vue/updateWebpackConfig')

module.exports = (storybookBaseConfig, configType, defaultConfig) => {
  // Return the altered config
  return updateWebpackConfig(storybookBaseConfig)
}
```

my `.storybook/config.js`
```js
import { configure, addDecorator } from '@storybook/vue'
import { withReadme } from 'storybook-readme'

import Readme from '../README.md'

addDecorator(withReadme(Readme))

configure(() => require('../src/stories'), module)
```
---
<details>
 <summary>Side note</summary>
If I try to extend default storybook config by

```js
module.exports = (storybookBaseConfig, configType, defaultConfig) => {
  return updateWebpackConfig(defaultConfig)
}
```

, I got this error

```bash
yarn run v1.2.1
$ build-storybook --static-dir static --output-dir .storybook/dist
@storybook/vue v3.3.10

=> Loading custom addons config.
=> Loading custom webpack config (full-control mode).
/home/wildan/Projects/Examples/myvu-component/node_modules/storybook-readme/env/vue/updateWebpackConfig.js:6
  storybookBaseConfig.module.rules = storybookBaseConfig.module.rules.map(function (rule) {
                      ^

TypeError: Cannot read property 'module' of undefined
    at module.exports (/home/wildan/Projects/Examples/myvu-component/node_modules/storybook-readme/env/vue/updateWebpackConfig.js:6:23)
    at module.exports (/home/wildan/Projects/Examples/myvu-component/.storybook/webpack.config.js:18:10)
    at exports.default (/home/wildan/Projects/Examples/myvu-component/node_modules/@storybook/vue/dist/server/config.js:62:12)
    at Object.<anonymous> (/home/wildan/Projects/Examples/myvu-component/node_modules/@storybook/vue/dist/server/build.js:77:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wildan/Projects/Examples/myvu-component/node_modules/@storybook/vue/bin/build.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by tuchk4** [comment]
Seems this issue should be related to stroybook repo, not to this addon. Becasue `md` loader is configured there.

@ndelangen any ideas?
