### ISSUE TITLE
Error using typescript

### ISSUE THREAD

**Issue by wilomgfx** [tuchk4/storybook-readme#80]
Im getting this error when using typescript, kinda weird :o!
![image](https://user-images.githubusercontent.com/6611491/42647770-ec1f9a4e-85d2-11e8-816f-e585ebc6ffeb.png)

**Comment by tuchk4** [comment]
Could you please provide example of the story  with such error

**Comment by wilomgfx** [comment]
Fixed it by changing my markdown import from 

`import * as ButtonReadme from '../../src/components/Button/README.md';`

to 

`import ButtonReadme from '../../src/components/Button/README.md';`

**Comment by Wgil** [comment]
I'm also getting this error.

My current story:
```
import * as React from "react";

import { storiesOf } from "@storybook/react";
import {withDocs} from 'storybook-readme'
import ButtonDocs from './README.md'

storiesOf("Button", module)
  .add("Default",
    withDocs(ButtonDocs, () => (
      <Button
        label='Default button'
        disabled={false}
        onClick={() => alert('hello there')}
    />
    )
  ))
```

The error:

```
Cannot read property 'split' of undefined
    TypeError: Cannot read property 'split' of undefined
    at normalized.reduce.docsBeforePreview (http://localhost:6006/vendors~main.7391e15b48d46b3ddc2c.bundle.js:77182:68)
    at Array.reduce (<anonymous>)
    at push../node_modules/storybook-readme/services/normalizeDocs.js.exports.default (http://localhost:6006/vendors~main.7391e15b48d46b3ddc2c.bundle.js:77181:28)
    at http://localhost:6006/vendors~main.7391e15b48d46b3ddc2c.bundle.js:75415:45
    at Object.withDocs (http://localhost:6006/vendors~main.7391e15b48d46b3ddc2c.bundle.js:75431:68)
    at Object.<anonymous> (http://localhost:6006/main.7391e15b48d46b3ddc2c.bundle.js:158:40)
    at Object../components/Button/Button.stories.tsx (http://localhost:6006/main.7391e15b48d46b3ddc2c.bundle.js:198:30)
    at __webpack_require__ (http://localhost:6006/runtime~main.7391e15b48d46b3ddc2c.bundle.js:782:30)
    at fn (http://localhost:6006/runtime~main.7391e15b48d46b3ddc2c.bundle.js:150:20)
    at webpackContext (http://localhost:6006/main.7391e15b48d46b3ddc2c.bundle.js:64:9)
  ```

**Comment by Wgil** [comment]
Get it working declaring
```import * as ButtonReadme from './README.md'```
and
```declare module '*.md';```

**Comment by jnhooper** [comment]
I was struggling with this for a while and my issue ended up being i forgot to include my typings in `include` in tsconfig.json
```
 "compilerOptions": {
        "allowJs": true,
        "outDir": "./dist",
        "sourceMap": true,
        "noImplicitAny": false,
        "module": "es6",
        "target": "es5",
        "jsx": "react",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "baseUrl": "./",
        "paths": {
            "interfaces/*": ["src/interfaces/*"]
        },
        "typeRoots": [
            "node_modules/@types", "typings.d.ts"
          ],
    },
    "include": [
        "./src", "typings.d.ts"
    ],
```
